version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: booking_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: booking_app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN} 
      
  frontend:
    build:
      context: ../booking-frontend
    container_name: booking_frontend
    restart: always
    ports:
      - '80:80'
    depends_on:
      - app

volumes:
  postgres_data:
